import numpy as np

# =============================================================================
# Compact Character-Level Word Embedding
#
# A training-free, deterministic algorithm that embeds words into fixed-size
# vectors where L2 distance correlates with edit distance:
#   - Small misspellings / morphological changes → small distance
#   - Unrelated words / reorderings             → large distance
#
# Key design choices:
#   1. Multi-scale n-grams (2,3,4) — captures both fine and coarse patterns
#   2. Sparse contractive state matrix (ESN-inspired) — richer reservoir
#      dynamics than dense random matrices
#   3. Step-count normalization — makes distances comparable across word
#      lengths without collapsing to unit sphere
#   4. Start boundary marker (^) — anchors prefix context
# =============================================================================


# -----------------------------
# Utilities
# -----------------------------

def l2(a, b):
    """Euclidean distance between two embedding vectors."""
    return np.linalg.norm(a - b)


# -----------------------------
# Alphabet + encoding
# -----------------------------

class CharEncoder:
    """Maps characters to encoding vectors and builds n-gram input vectors
    by concatenating the encodings of each character in the n-gram.

    Supports a similarity dict for soft encoding:
        similarities = {'ö': [('o', 0.7), ('oe', 0.5)], ...}

    Single-char targets (e.g. 'o') produce soft encoding vectors:
        encode('ö') = normalize(onehot('ö') + 0.7 * onehot('o'))

    Multi-char targets (e.g. 'oe') are ignored here — they are handled
    by WordEmbedder via expansion blending.

    Characters without similarity entries get pure one-hot vectors,
    so existing behavior is preserved exactly.
    """

    def __init__(self, alphabet, similarities=None):
        self.alphabet = alphabet
        self.K = len(alphabet)
        self.index = {c: i for i, c in enumerate(alphabet)}
        # Precompute encoding vectors (soft or one-hot) for every char
        self._encoding = {}
        for c in alphabet:
            self._encoding[c] = self._build_encoding(c, similarities)

    def _build_encoding(self, c, similarities):
        """Build the encoding vector for character c.
        If c has single-char similarities, blend their one-hots in."""
        v = np.zeros(self.K)
        if c in self.index:
            v[self.index[c]] = 1.0
        if similarities and c in similarities:
            for target, weight in similarities[c]:
                if len(target) == 1 and target in self.index:
                    v[self.index[target]] += weight
            # Normalize so the vector has unit L2 norm
            norm = np.linalg.norm(v)
            if norm > 0:
                v = v / norm
        return v

    def encode(self, c):
        """Return the encoding vector for a character (soft or one-hot)."""
        if c in self._encoding:
            return self._encoding[c]
        # Unknown character — zero vector
        return np.zeros(self.K)

    def ngram_vector(self, gram):
        """Concatenate encoding vectors for each character in the n-gram.
        Result is a vector of dimension n * K."""
        return np.concatenate([self.encode(c) for c in gram])


# -----------------------------
# Sequential embedder
# -----------------------------

class WordEmbedder:
    """Hybrid sequential + bag-of-ngrams word embedder using multi-scale character n-grams.

    Architecture:
        - For each n-gram scale (2, 3, 4), a dedicated projection matrix B
          maps the concatenated one-hot input into the state space.
        - A sparse contractive matrix A drives a forward recurrent pass
          over the n-grams (left → right).
        - The residual update  v = v + tanh(A @ v + B @ x)  accumulates
          each n-gram's contribution as a bounded increment, ensuring that
          small edits produce small changes in the final state.
        - A bag-of-ngrams component averages all projected n-gram vectors,
          making suffix additions (e.g. "orange" → "oranges") low-cost.
        - The sequential state is divided by sqrt(steps) to normalize
          for word length.

    Character similarity support:
        A similarity dict maps characters to a list of (target, weight) pairs:
            {'ö': [('o', 0.7), ('oe', 0.5)], 'ß': [('ss', 0.7)]}

        - Single-char targets (e.g. ö→o): handled via soft encoding in
          CharEncoder — the one-hot for ö is blended with o's one-hot,
          so every n-gram containing ö becomes close to the same n-gram
          with o. Zero overhead for characters without similarities.

        - Multi-char targets (e.g. ö→oe, ß→ss): handled via expansion
          blending — alternate word forms are generated by replacing
          each special char with its multi-char expansion, embedded
          separately, and blended with the original embedding weighted
          by the similarity weight.

    Note on boundary markers: only a start marker ^ is used. An end
    marker $ was tested but caused large distance shifts when letters
    are appended at the end (e.g. "orange" vs "oranges"), because $
    moves and invalidates all nearby n-grams. Without $, adding a
    suffix only appends new n-grams without modifying existing ones.

    Parameters:
        alphabet     : str    — character set including start boundary marker ^
        scales       : tuple  — n-gram sizes to use (default: bigrams, trigrams, 4-grams)
        d            : int    — embedding dimension
        alpha        : float  — spectral radius target for A matrix (< 1 for stability)
        sparsity     : float  — fraction of zero entries in A (0.85 = 85% zeros)
        seed         : int    — random seed for reproducibility
        similarities : dict   — character similarity mappings (default: None)
        length_norm  : float  — length normalization strength in [0, 1] (default: 1.0)
                                1.0 = full normalization (current default; long words
                                      produce smaller per-edit distances)
                                0.0 = no normalization (per-edit distance is independent
                                      of word length)
    """

    def __init__(self, alphabet, scales=(2, 3, 4), d=64, alpha=0.9, sparsity=0.85,
                 seed=0, similarities=None, length_norm=1.0):
        np.random.seed(seed)

        self.similarities = similarities or {}
        self.encoder = CharEncoder(alphabet, similarities=self.similarities)
        self.K = self.encoder.K
        self.scales = scales
        self.d = d
        self.length_norm = np.clip(length_norm, 0.0, 1.0)

        # Sparse contractive A matrix for sequential pass.
        self.A = self._make_sparse_A(d, alpha, sparsity)

        # One projection matrix B per n-gram scale (used for both sequential and bag).
        # Each B maps from n*K dimensional input to d dimensional state space.
        self.Bs = {}
        for n in scales:
            input_dim = n * self.K
            self.Bs[n] = np.random.randn(d, input_dim) / np.sqrt(input_dim)

        # Precompute multi-char expansions from the similarity dict.
        # Maps char → list of (replacement_string, weight).
        self._expansions = {}
        for c, targets in self.similarities.items():
            for target, weight in targets:
                if len(target) > 1:
                    self._expansions.setdefault(c, []).append((target, weight))

    @staticmethod
    def _make_sparse_A(d, alpha, sparsity):
        """Create a sparse contractive matrix.

        1. Sample dense Gaussian matrix
        2. Zero out entries with probability = sparsity
        3. Rescale so spectral norm = alpha (< 1)

        The spectral norm constraint guarantees the recurrent dynamics
        are contractive — the state doesn't blow up over long words.
        """
        A = np.random.randn(d, d)
        mask = np.random.rand(d, d) > sparsity
        A = A * mask
        spectral_norm = np.linalg.norm(A, ord=2)
        if spectral_norm > 0:
            A = alpha * A / spectral_norm
        return A

    def _collect_ngrams(self, word):
        """Extract all n-grams at all scales, ordered by position then scale.

        At each character position, we extract n-grams of increasing size.
        This interleaving means the recurrent state sees fine-grained (bigram)
        and coarse (4-gram) signals at each position before advancing.
        """
        ngrams = []
        for i in range(len(word)):
            for n in self.scales:
                if i + n <= len(word):
                    ngrams.append((n, word[i:i+n]))
        return ngrams

    def _expand_word(self, word):
        """Generate expanded word forms by replacing characters with multi-char targets.

        For each character that has multi-char expansions, generates an alternate
        form with that character replaced. Each expansion is independent — if a
        word has multiple expandable characters, each produces its own variant.

        Returns:
            list of (expanded_word, weight) pairs. Empty if no expansions apply.

        Example with similarities = {'ö': [('oe', 0.5)], 'ß': [('ss', 0.7)]}:
            "größe" → [("groesse", 0.5), ("größe"→"grosse" not generated here
                        because ö and ß are expanded independently)]
            Actually: each char independently:
            "größe" → [("groöße"? no...) ]

        Actually, for each expandable char at each position, one variant is
        generated with that single char replaced. Multiple expandable chars
        in the same word each produce separate variants.
        """
        expansions = []
        for i, c in enumerate(word):
            if c in self._expansions:
                for replacement, weight in self._expansions[c]:
                    expanded = word[:i] + replacement + word[i+1:]
                    expansions.append((expanded, weight))
        return expansions

    def _embed_raw(self, word):
        """Core embedding logic (no expansion blending). Returns unnormalized vector.

        Architecture: sequential (forward) + bag-of-ngrams hybrid.

        Length normalization is controlled by self.length_norm ∈ [0, 1]:
            v = v_seq / T^(0.5 * length_norm) + v_bag_sum / T^(length_norm)

        At length_norm=1.0: v_seq/√T + sum/T  (default, length-dependent)
        At length_norm=0.0: v_seq + sum        (length-invariant per-edit distances)
        """
        word = '^' + word.lower()
        ngrams = self._collect_ngrams(word)
        total_steps = len(ngrams)

        # Sequential pass (left to right)
        v_seq = np.zeros(self.d)
        # Bag-of-ngrams accumulator
        v_bag = np.zeros(self.d)

        for n, gram in ngrams:
            x = self.encoder.ngram_vector(gram)
            projected = self.Bs[n] @ x
            v_seq = v_seq + np.tanh(self.A @ v_seq + projected)
            v_bag = v_bag + projected

        # Apply length normalization with configurable strength.
        # Exponents scale from full (1.0, 0.5) to none (0.0, 0.0).
        ln = self.length_norm
        v_bag = v_bag / (total_steps ** ln)
        v_seq = v_seq / (total_steps ** (0.5 * ln))

        return v_seq + v_bag

    def embed(self, word, normalize=False):
        """Embed a word into a d-dimensional vector.

        If the word contains characters with multi-char similarity targets,
        expanded word forms are generated and their embeddings are blended
        with the original:

            v = v_original + w1 * v_expansion1 + w2 * v_expansion2 + ...
            v = v / (1 + w1 + w2 + ...)

        This weighted average pulls the embedding of e.g. "König" toward
        "Koenig" proportionally to the similarity weight, while characters
        with only single-char similarities (soft encoding) are already
        handled inside the n-gram vectors.
        """
        v = self._embed_raw(word)

        # Expansion blending for multi-char similarities
        if self._expansions:
            expanded_forms = self._expand_word(word.lower())
            if expanded_forms:
                total_weight = 1.0
                for exp_word, weight in expanded_forms:
                    v_exp = self._embed_raw(exp_word)
                    v = v + weight * v_exp
                    total_weight += weight
                v = v / total_weight

        if normalize:
            v = v / (np.linalg.norm(v) + 1e-8)

        return v

    def save_matrices(self, filepath):
        """Save random matrices A and Bs to a simple binary file for C++ loading.
        
        Binary format:
            - num_scales (uint32)
            - d (uint32) 
            - K (uint32)
            - scales array (uint32 * num_scales)
            - A matrix: d*d floats (float32)
            - For each scale in order:
                - B matrix: d*(scale*K) floats (float32)
        """
        import struct
        
        with open(filepath, 'wb') as f:
            # Write header
            f.write(struct.pack('I', len(self.scales)))  # num_scales
            f.write(struct.pack('I', self.d))  # dimensions
            f.write(struct.pack('I', self.K))  # alphabet size
            
            # Write scales array
            for scale in self.scales:
                f.write(struct.pack('I', scale))
            
            # Write A matrix (flatten to row-major order)
            A_flat = self.A.astype(np.float32).flatten()
            f.write(A_flat.tobytes())
            
            # Write B matrices in scale order
            for scale in self.scales:
                B_flat = self.Bs[scale].astype(np.float32).flatten()
                f.write(B_flat.tobytes())
    
    @classmethod
    def load_matrices(cls, filepath, alphabet, similarities=None, length_norm=1.0):
        """Load matrices from binary file and create embedder without regenerating random matrices.
        
        Parameters:
            filepath: path to binary matrix file
            alphabet: character set (must match saved embedder)
            similarities: character similarities (must match saved embedder)
            length_norm: normalization strength
        
        Returns:
            WordEmbedder instance with loaded matrices
        """
        import struct
        
        with open(filepath, 'rb') as f:
            # Read header
            num_scales = struct.unpack('I', f.read(4))[0]
            d = struct.unpack('I', f.read(4))[0]
            K = struct.unpack('I', f.read(4))[0]
            
            # Read scales array
            scales = tuple(struct.unpack('I', f.read(4))[0] for _ in range(num_scales))
            
            # Create embedder with dummy seed (won't be used)
            embedder = cls(alphabet, scales=scales, d=d, alpha=0.9, sparsity=0.85, 
                          seed=0, similarities=similarities, length_norm=length_norm)
            
            # Read A matrix
            A_size = d * d
            A_bytes = f.read(A_size * 4)
            embedder.A = np.frombuffer(A_bytes, dtype=np.float32).reshape(d, d).astype(np.float64)
            
            # Read B matrices
            for scale in scales:
                B_rows = d
                B_cols = scale * K
                B_size = B_rows * B_cols
                B_bytes = f.read(B_size * 4)
                embedder.Bs[scale] = np.frombuffer(B_bytes, dtype=np.float32).reshape(B_rows, B_cols).astype(np.float64)
        
        return embedder


